<?php

namespace eProcess\EntityBundle\Entity;

/**
 * AchatTable
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AchatDepartementTable extends \Doctrine\ORM\EntityTable
{
}
