<?php

namespace eProcess\EntityBundle\Entity;

/**
 * ActionTable
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionTable extends \Doctrine\ORM\EntityTable
{
}
