<?php

namespace eProcess\EntityBundle\Entity;

/**
 * CheckListTable
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckListTable extends \Doctrine\ORM\EntityTable
{
    
   
}
