<?php

namespace eProcess\EntityBundle\Entity;

/**
 * FichierTable
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichierTable extends \Doctrine\ORM\EntityTable
{
}
