<?php

namespace eProcess\EntityBundle\Entity;

/**
 * TransfertFactureTable
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransfertFactureTable extends \Doctrine\ORM\EntityTable
{
}
